import type { Metadata } from 'next';
import '@/styles/globals.css';
import { noto } from '@/fonts/noto';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fr' className={`h-full ${noto.className}`}>
      <body className='h-full flex flex-col'>{children}</body>
    </html>
  );
}
